services:
  WEBcoast\DeferredImageProcessing\Command\ProcessCommand:
    tags:
      - name: 'console.command'
        command: 'deferred_image_processing:process'
        description: 'Process all entries in deferred image processing file list'
        hidden: false
